services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5555
    ports:
      - "3333:3000"
    restart: always
    depends_on:
      - backend
    

  backend:
    build:
      context: .
      dockerfile: dockerfile-backend
    ports:
      - "5555:8000"
    restart: always
    