trial_id: Trial ID for the ROS device. No spaces or special characters allowed.
devices: List of devices to subscribe to. Each device should have a 'namespace' and
  a list of 'rostopics' to subscribe to. 'attributes' are optional and can be used
  to set the attributes of the device.
